# Generated by Django 3.0.6 on 2021-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewjob',
            name='job_choices',
            field=models.CharField(choices=[('LAB NABL', 'LAB NABL'), ('LAB TRAC', 'LAB TRAC'), ('ONSITE NABL', 'ONSITE NABL'), ('ONSITE TRAC', 'ONSITE TRAC')], default='LAB NABL', max_length=50),
        ),
    ]
