# Generated by Django 3.0.6 on 2021-12-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0002_auto_20211221_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuc_name', models.CharField(max_length=200)),
                ('workinstruction', models.CharField(max_length=200)),
                ('Is_Standard', models.CharField(max_length=200)),
                ('uncertainity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_job_id', models.CharField(max_length=200, null=True)),
                ('cust_spec_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(choices=[('DIMENSION_LAB', 'Dimension Lab'), ('PRESSURE_LAB', 'Pressure Lab'), ('THERMAL_LAB', 'Thermal Lab'), ('ELECTRICAL_LAB', 'Electrical Lab'), ('ONSITE', 'On Site')], default='DIMENSION_LAB', max_length=50)),
                ('sr_no', models.CharField(max_length=200)),
                ('id_no', models.CharField(max_length=200)),
                ('least_count', models.FloatField(default='', max_length=200)),
                ('accuracy', models.FloatField()),
                ('low_range', models.FloatField()),
                ('high_range', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('inst_location', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('OK', 'OK'), ('NOT_GOOD', 'NOT GOOD')], default='OK', max_length=50)),
                ('nabl', models.BooleanField()),
                ('cal_frequency', models.CharField(choices=[('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEAR', '2 Year'), ('3_YEAR', '3 Year')], default='1_YEAR', max_length=50)),
                ('sp_req', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inst_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_name', to='calibration_management_app.UUC')),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration_management_app.AddNewJob')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration_management_app.Make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration_management_app.Model')),
            ],
        ),
    ]
