# Generated by Django 3.0.6 on 2021-12-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0005_auto_20211222_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration_management_app.Staffs'),
        ),
    ]
