# Generated by Django 3.0.6 on 2021-12-22 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0006_auto_20211222_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='now',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
