# Generated by Django 3.0.6 on 2021-12-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0011_finalcert'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcert',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finalcert',
            name='comment',
            field=models.CharField(default='Review Pending', max_length=500),
        ),
    ]
