# Generated by Django 3.0.6 on 2021-12-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0012_auto_20211224_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcert',
            name='comment',
            field=models.CharField(default='In Process', max_length=500),
        ),
    ]
