# Generated by Django 3.0.6 on 2021-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0013_auto_20211224_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcert',
            name='image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
        migrations.AddField(
            model_name='finalcert',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
