# Generated by Django 3.0.6 on 2021-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0014_auto_20211224_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalcert',
            name='image',
        ),
        migrations.RemoveField(
            model_name='finalcert',
            name='url',
        ),
        migrations.AddField(
            model_name='finalcert',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
