# Generated by Django 3.0.6 on 2021-12-24 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0017_auto_20211224_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='now',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
