# Generated by Django 3.0.6 on 2021-12-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0023_auto_20211228_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcert',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, upload_to='media/qr_codes'),
        ),
    ]
