# Generated by Django 3.0.6 on 2021-12-31 05:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0025_auto_20211229_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='contact',
        ),
        migrations.AddField(
            model_name='party',
            name='business_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='party',
            name='fax_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='party',
            name='home_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='job_position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='party',
            name='mobile_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='webpage',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.EmailField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
