# Generated by Django 3.0.6 on 2021-12-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0026_auto_20211231_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
