# Generated by Django 3.0.6 on 2021-12-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_management_app', '0027_party_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], default='NORMAL', max_length=50),
        ),
    ]
